### PR TITLE
updates to team page

### PR DESCRIPTION
**Pull request by damianodamiani**
hey, so I cleaned up a bit the team page, added dates here and there, and updated my (Damian) bio page. Please take a look at the changes and approve / or add further changes to the team page. I suggest merging this as is, and then, in case anyone will change their bios, open new branches for these changes whenever necessary.

### CODE REVIEW

**Comment by damianodamiani** [comment]
should we add dates for the research assistants too @LenaHenningsen? like just the year(s) when they worked with us, if yes please provide the info

**Review by LenaHenningsen — COMMENTED** [review]
Thanks a lot - though as the project is almost over, please make only one list for the research assistants, to keep it simple. Thanks!

**Comment by damianodamiani** [comment]
no problem, RAs as one list now again

**Comment by damianodamiani** [comment]
please review and merge and close if all ok @LenaHenningsen

**Review by LenaHenningsen — APPROVED** [review]

**Pull request merged**
