### PR TITLE
post for Daytons MC article

### PR DESCRIPTION
**Pull request by damianodamiani**
hey, Dayton asked me to create a post for his article as its topic fits nicely into READCHINA's scope -- however, I (again) cant do local builds, or rather, my local build does not show the post... so please review and tell me if all is fine, someone, thanks!

### CODE REVIEW

**Comment by damianodamiani** [comment]
no idea why, I also cannot see it in the build -- but the post is there...

**Comment by damianodamiani** [comment]
my bad, totally forgot about the .md ending! sorry. now all works good, ready to merge if approved @LenaHenningsen

**Comment by whalekeykeeper** [comment]
> my bad, totally forgot about the .md ending! sorry. now all works good, ready to merge if approved @LenaHenningsen

Should I approve and merge it?

**Comment by damianodamiani** [comment]
yes please!

**Review by whalekeykeeper — APPROVED** [review]

**Comment by LenaHenningsen** [comment]
Yes please. Thanks! 

 

Von: Qin Gu ***@***.***>
Antworten an: "readchina/readchina.github.io" ***@***.***>
Datum: Donnerstag, 13. April 2023 um 10:48
An: "readchina/readchina.github.io" ***@***.***>
Cc: LenaHenningsen ***@***.***>, Mention ***@***.***>
Betreff: Re: [readchina/readchina.github.io] post for Daytons MC article (PR #280)

 

my bad, totally forgot about the .md ending! sorry. now all works good, ready to merge if approved @LenaHenningsen

Should I approve and merge it?

**Pull request merged**
