### PR TITLE
added post for dvcs volume

### PR DESCRIPTION
**Pull request by damianodamiani**
Please fill in the gaps -- @LenaHenningsen and @EveYLin please add the abstracts of your chapters in the respective fields, as well as any other information you might want to add to the post. The chapter order follows the order in the EV, happy to change that in any other way if needed.

### CODE REVIEW

**Comment by damianodamiani** [comment]
so, no PR merger until the info is added :) And, the post has a future date for the same day as the 'official' publication date (nov 22) so you won't see it in the local build.

**Comment by damianodamiani** [comment]
just an update, the volume is now officially available as of yesterday so we could merge this whenever you add your abstracts etc @EveYLin @LenaHenningsen

**Review by duncdrum — CHANGES_REQUESTED** [review]
It’s not that my public key is a secret, but it  certainly doesn’t belong with the post. Please remove it from the website repo

**Comment by whalekeykeeper** [comment]
Hi Duncan, the public key file is removed, while keeping the change in the file under Posts. I used the following commands:
```
git reset --soft HEAD^

git reset HEAD PUBLIC_KEY_FILE

git commit --amend -m "withdrawal the public key file"

git push --force
```
I hope that's correct.




Hi Eve @EveYLin , would be nice if you could have a quick look at "Files changed" to double check

**Review by duncdrum — APPROVED** [review]

**Pull request merged**
