### PR TITLE
Update RAs views

### PR DESCRIPTION
**Pull request by whalekeykeeper**
Three Vega views on ReadAct page of the ReadChina website are updated. They are:
Reading acts with autobiography sources
Reading Acts in Chinese Fictional Texts ( specified with science fiction genre for the source of reading acts)
Reading Acts in Chinese Fictional Texts

The text of the ReadAct page are updated accordingly.

See #277

### CODE REVIEW

**Comment by LenaHenningsen** [comment]
Hi Qin, lovely work! A few minor things:
1) Can you please move the chart for the autobiographical sources up in between the paragraphs where there first one ends on " also, while some were officially endorsed, many others were forbidden at the time, or only circulating internally." and the second reads: " also, while some were officially endorsed, many others were forbidden at the time, or only circulating internally."
2) delete the header: Reading acts with autobiography sources
3) Can you italicize book titles in this paragraph:
This, however, has to do with the fact that the sample consists of a number of SF stories, of three stories by Ah Cheng and of the scar literature short story “The Class Teacher” (班主任 by Liu Xinwu 刘心武). And throughout this latter story, the characters discuss the novel, its contents and its ideological implications ([Henningsen 2020](https://www.researchgate.net/publication/342521654_POACHING_WORLD_LITERATURE_IN_CHINA%27S_LONG_1970s_Asian_Journal_of_African_Studies#fullTextFileContent)). So, while _The Gadfly_ definitely was an important literary text in Maoist China, the graph exaggerates its importance. Therefore, in a next step, we narrow down the reading acts to those which occur in the science fiction stories in the sample. Of the vast literary output of Chinese SF in recent years, this sample is taken from a number of SF novels and anthologies of SF translated into foreign languages (English, German) over the past decades, thus containing a small sample of texts from the first post-Maoist wave of science fiction and a somewhat more substantial sample of more recent texts, when not only SF is blossoming in China, but also finding interested readers abroad. Once again, this does not represent all SF ever written in China, but a slightly larger sample that allows drawing a few conclusions.
AND IN THIS ONE TOO
Rachel Carson’s _The Silent Spring_ is boasting most records as it is read several times in Liu Cixin’s famous novel The Three Body Problem. Other than that, we can see that readers in Chinese SF read a wide scope of world literature, ranging from the _Iliad_ to _1984_ or Douglas Adams’ _The Restaurant at the End of the Universe_, as well as Chinese texts ranging from _The Journey to the West_ to Lu Xun’s “Diary of a Madman”. With reading acts and other intertextual references, Chinese SF thus clearly positions itself within the canon of world literature and emphasizes its own literary status.
AND HERE TOO
Given that this graph combines sources from different times and – for the fictional texts – a sample that is anything but representative, the explanatory value of this graph is limited. After all, _The Gadfly_ clearly cannot be seen as the text most widely in China. However, this record may remind us of the fact that at a certain point in Chinese history (throughout the Mao years and into the early post-Mao years), it definitely was an important text. After all, of the 20 mentions here, 16 relate to “The Class Teacher” – and the remaining for to autobiographical texts about the 1970s.
4) Change ILIAD to Iliad
5) The section entitled "popular authors" (i.e. section heading, paragraph starting "The previous views look", graph and second paragraph starting "It seems that the classics, b") should be moved up, to after the section with the musical works, i.e. AFTER the paragraph "The reading (or consumption) of other cultural products shows a similar pattern to the reading of “textual text”, as officially endorsed items were read side-by-side with others which were frowned upon, or condemned at the time (as, for example, The Butterfly Violin Concerto)."

Thanks a lot for all your work and let me know if things are unclear! All best Lena

**Comment by whalekeykeeper** [comment]
> Hi Qin, lovely work! A few minor things:
> 
> 1. Can you please move the chart for the autobiographical sources up in between the paragraphs where there first one ends on " also, while some were officially endorsed, many others were forbidden at the time, or only circulating internally." and the second reads: " also, while some were officially endorsed, many others were forbidden at the time, or only circulating internally."
> 2. delete the header: Reading acts with autobiography sources
> 3. Can you italicize book titles in this paragraph:
>    This, however, has to do with the fact that the sample consists of a number of SF stories, of three stories by Ah Cheng and of the scar literature short story “The Class Teacher” (班主任 by Liu Xinwu 刘心武). And throughout this latter story, the characters discuss the novel, its contents and its ideological implications ([Henningsen 2020](https://www.researchgate.net/publication/342521654_POACHING_WORLD_LITERATURE_IN_CHINA%27S_LONG_1970s_Asian_Journal_of_African_Studies#fullTextFileContent)). So, while _The Gadfly_ definitely was an important literary text in Maoist China, the graph exaggerates its importance. Therefore, in a next step, we narrow down the reading acts to those which occur in the science fiction stories in the sample. Of the vast literary output of Chinese SF in recent years, this sample is taken from a number of SF novels and anthologies of SF translated into foreign languages (English, German) over the past decades, thus containing a small sample of texts from the first post-Maoist wave of science fiction and a somewhat more substantial sample of more recent texts, when not only SF is blossoming in China, but also finding interested readers abroad. Once again, this does not represent all SF ever written in China, but a slightly larger sample that allows drawing a few conclusions.
>    AND IN THIS ONE TOO
>    Rachel Carson’s _The Silent Spring_ is boasting most records as it is read several times in Liu Cixin’s famous novel The Three Body Problem. Other than that, we can see that readers in Chinese SF read a wide scope of world literature, ranging from the _Iliad_ to _1984_ or Douglas Adams’ _The Restaurant at the End of the Universe_, as well as Chinese texts ranging from _The Journey to the West_ to Lu Xun’s “Diary of a Madman”. With reading acts and other intertextual references, Chinese SF thus clearly positions itself within the canon of world literature and emphasizes its own literary status.
>    AND HERE TOO
>    Given that this graph combines sources from different times and – for the fictional texts – a sample that is anything but representative, the explanatory value of this graph is limited. After all, _The Gadfly_ clearly cannot be seen as the text most widely in China. However, this record may remind us of the fact that at a certain point in Chinese history (throughout the Mao years and into the early post-Mao years), it definitely was an important text. After all, of the 20 mentions here, 16 relate to “The Class Teacher” – and the remaining for to autobiographical texts about the 1970s.
> 4. Change ILIAD to Iliad
> 5. The section entitled "popular authors" (i.e. section heading, paragraph starting "The previous views look", graph and second paragraph starting "It seems that the classics, b") should be moved up, to after the section with the musical works, i.e. AFTER the paragraph "The reading (or consumption) of other cultural products shows a similar pattern to the reading of “textual text”, as officially endorsed items were read side-by-side with others which were frowned upon, or condemned at the time (as, for example, The Butterfly Violin Concerto)."
> 
> Thanks a lot for all your work and let me know if things are unclear! All best Lena

Thanks for detailed instruction. All the requirements are done. One question left and also one observation to mention. 

The question is: Is "The Class Teacher" counted as a book title? And its Chinese translation "班主任"? And "Diary of a Madman"? 

And the observation to mention is that: The view in the section "Popular authors" seems to have a lot of whitespace below the picture. I checked, it looks a bit suspicious but the output is correct. If one scroll the picture to the very right side, one can see the illustrations of what color represents what.

**Comment by LenaHenningsen** [comment]
Diary of a Madman and The Class Teacher are both short stories, therefore they should be given in "...", but not in italics.
Thanks so much!

**Comment by whalekeykeeper** [comment]
> 



> Diary of a Madman and The Class Teacher are both short stories, therefore they should be given in "...", but not in italics. Thanks so much!

Thanks for illustration. They are kept in the way of using double quotes. Just checked again.

**Comment by whalekeykeeper** [comment]
May you wait to merge this PR until tomorrow(Monday) instead of today?  I am double checking the data in views right now. Friday I worked 4 hours on learning more about SQL and hasn't finished the checking of the views on Friday. I'll write you more via basecamp soon (Wanted to write you yesterday but I was thinking it might be better to not write you on weekend).

**Comment by LenaHenningsen** [comment]
Take your time, just let me know once you are happy with everything. (And sorry for writing back on a weekend!)

**Comment by whalekeykeeper** [comment]
> Take your time, just let me know once you are happy with everything. (And sorry for writing back on a weekend!)

thanks and no problem. I feel I started the messages anyway... Sorry

**Comment by whalekeykeeper** [comment]
It seems that [`textql`](https://github.com/dinedal/textql) is not supporting strings concatenation. I am going to open an issue there and meanwhile do the firstname-familyname_concatenation manually (with Python actually).

**Comment by whalekeykeeper** [comment]
Hi Lena, once the latest PR on ReadAct is merged, this PR can be merged as well.

**Comment by whalekeykeeper** [comment]
I need a bit time to manually go through view tables for eliminating duplicated rows. Will make this PR ready after that.

**Comment by LenaHenningsen** [comment]
Sure, no worries. I am off now and have made a note of it for tomorrow. You can just send me a message once you are done  and happy with merging.

 

Von: Qin Gu ***@***.***>
Antworten an: "readchina/readchina.github.io" ***@***.***>
Datum: Dienstag, 20. Juni 2023 um 14:36
An: "readchina/readchina.github.io" ***@***.***>
Cc: Lena Henningsen ***@***.***>, Review requested ***@***.***>
Betreff: Re: [readchina/readchina.github.io] Update RAs views (PR #289)

 

I need a bit time to manually go through view tables for eliminating duplicated rows. Will make this PR ready after that.

**Comment by whalekeykeeper** [comment]
> Sure, no worries. I am off now and have made a note of it for tomorrow. You can just send me a message once you are done  and happy with merging. Von: Qin Gu ***@***.***> Antworten an: "readchina/readchina.github.io" ***@***.***> Datum: Dienstag, 20. Juni 2023 um 14:36 An: "readchina/readchina.github.io" ***@***.***> Cc: Lena Henningsen ***@***.***>, Review requested ***@***.***> Betreff: Re: [readchina/readchina.github.io] Update RAs views (PR #289) I need a bit time to manually go through view tables for eliminating duplicated rows. Will make this PR ready after that. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because your review was requested.Message ID: ***@***.***>

Hi Lena, could you merge the PR on ReadAct first, and then this one?

**Review by LenaHenningsen — COMMENTED** [review]
Hi Qin, it all looks nice with one exception. The first chart (RA from autobiographical sources) is quite odd: it now only contains 1 item... Could you double check? The rest looks beautiful. Lena

**Comment by whalekeykeeper** [comment]
> Hi Qin, it all looks nice with one exception. The first chart (RA from autobiographical sources) is quite odd: it now only contains 1 item... Could you double check? The rest looks beautiful. Lena

Sorry! Gonna check now

**Comment by LenaHenningsen** [comment]
Hooray

**Pull request merged**
